<?php $this->layout('layouts/email'); ?>

<?php $this->section('content') ?>
    <p>Hello <?= $account->name ?>,</p>

    <p>Welcome to JapanTravel.com!</p>

    <p>The following username will allow you to login to JapanTravel via http://en.japantravel.com.</p>

    <p>Username: <?= $account->username ?></p>

    <p>We hope you will enjoy the <a href="http://en.japantravel.com/members">benefits</a> of being a member of Japan's largest travel community.<br>
    Discover ways to <a href="http://en.japantravel.com/about/rewards">earn points></a> and exchange for rewards in the <a href="http://en.japantravel.com/reward-store/">JapanTravel store</a>.</p>

    <p>Looking forward to seeing you around the site!</p>

    <p>Sincerely,<br>
    The JapanTravel Team</p>
<?php $this->replace() ?>
