<?php $this->layout('layouts/console', [
    'title' => 'Artists',
    // 'back_path' => $this->pathFor('console_home'),
]); ?>

<?php $this->section('breadcrumbs') ?>
    <li>
        <span class="show-for-sr">Current: </span> Register
    </li>
<?php $this->replace() ?>

<?php $this->section('content') ?>
    <div class="row">
    	<div class="small-12 columns">
            <form id="register_form" method="post" action="<?= $this->pathFor('auth_users_post') ?>">
                <label><?= $this->translate('first_name') ?>
                    <input type="text" class="form-control" name="first_name" placeholder="<?= $this->translate('first_name') ?>" value="<?= @$this->params['first_name'] ?>">
                </label>
                <label for="last_name"><?= $this->translate('last_name') ?>
                    <input type="text" class="form-control" name="last_name" placeholder="<?= $this->translate('last_name') ?>" value="<?= @$this->params['last_name'] ?>">
                </label>
                <label for="email"><?= $this->translate('email') ?>
                    <input type="text" class="form-control" name="email" placeholder="<?= $this->translate('email') ?>" value="<?= @$this->params['email'] ?>">
                </label>
                <label><?= $this->translate('password') ?>
                    <input type="password" class="form-control" name="password" placeholder="<?= $this->translate('password') ?>" value="">
                </label>

                <label class="checkbox-inline agreement">
                    <input name="agreement" type="checkbox"> <?= $this->translate('read_tc_agreement') ?>
                </label>

                <input type="hidden" name="<?= $this->csrf_name ?>" value="<?= $this->csrf_value ?>">

                <input type="text" class="more_info" name="more_info" value="" style="position: absolute; left: -9999px">

                <?php if(isset($this->params['returnTo'])): ?>
                    <input type="hidden" name="returnTo" value="<?= $this->params['returnTo'] ?>">
                <?php endif ?>

                <a href="<?= $this->pathFor('auth_session_login') ?>" class="button secondary">
                    <?= $this->translate('login_button') ?>
                </a>

                <button type="submit" class="button"><?= $this->translate('register_button') ?></button>
            </form>
        </div>
    </div>
<?php $this->replace() ?>
