Hello <?= $account->name ?>,

Welcome to JapanTravel.com!

The following username will allow you to login to JapanTravel via http://en.japantravel.com.

Username: <?= $account->username ?>

We hope you will enjoy the benefits (http://en.japantravel.com/members) of being a member of Japan's largest travel community.
Discover ways to earn points (http://en.japantravel.com/about/rewards) and exchange for rewards in the JapanTravel store (http://en.japantravel.com/reward-store/).

Looking forward to seeing you around the site!

Sincerely,
The JapanTravel Team
